language: node_js
sudo: false

os:
  - linux

node_js:
  - '6.11.3'
  - '8.5.0'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

after_script:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls